# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: buffer.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x62uffer.proto\x12\tmypackage\"\'\n\x0bTemperature\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04temp\x18\x04 \x01(\t\"\x1c\n\x02UF\x12\n\n\x02id\x18\x01 \x01(\t\x12\n\n\x02uf\x18\x02 \x01(\t\"$\n\x06\x44ollar\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0e\n\x06\x64ollar\x18\x02 \x01(\t\" \n\x04Game\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04game\x18\x02 \x01(\t\"\x07\n\x05\x45mpty\"\x1a\n\x07\x45xample\x12\x0f\n\x07\x45xample\x18\x01 \x01(\t2\xd0\x01\n\x08Servicer\x12:\n\x0eGetTemperature\x12\x10.mypackage.Empty\x1a\x16.mypackage.Temperature\x12(\n\x05GetUF\x12\x10.mypackage.Empty\x1a\r.mypackage.UF\x12\x30\n\tGetDollar\x12\x10.mypackage.Empty\x1a\x11.mypackage.Dollar\x12,\n\x07GetGame\x12\x10.mypackage.Empty\x1a\x0f.mypackage.Gameb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'buffer_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _TEMPERATURE._serialized_start=27
  _TEMPERATURE._serialized_end=66
  _UF._serialized_start=68
  _UF._serialized_end=96
  _DOLLAR._serialized_start=98
  _DOLLAR._serialized_end=134
  _GAME._serialized_start=136
  _GAME._serialized_end=168
  _EMPTY._serialized_start=170
  _EMPTY._serialized_end=177
  _EXAMPLE._serialized_start=179
  _EXAMPLE._serialized_end=205
  _SERVICER._serialized_start=208
  _SERVICER._serialized_end=416
# @@protoc_insertion_point(module_scope)
